const STORE_KEY = 'broken-soul-archive-v1';
const statuses = ['Утверждённый канон','Рабочая идея','Новое предложение','Требует уточнения'];
const statusClass = {'Утверждённый канон':'canon','Рабочая идея':'idea','Новое предложение':'new','Требует уточнения':'clarify'};
const sections = {
  scenes:{title:'Карта сцен', type:'scene', fields:['номер','название','сюжетный блок','время','место','главный персонаж','участники','краткое содержание','эмоциональная цель','последствия','связь с предыдущей и следующей сценой','заметки автора','вопросы без ответа','статус записи']},
  characters:{title:'Персонажи', type:'character', fields:['имя','род / статус','возраст','внешность','характер','сильные стороны','слабости','страхи','травмы','желания','отношения','путь','боевое искусство','важные сцены','развитие по книге','важные предметы','канон','рабочие идеи','требует уточнения']},
  lore:{title:'Лор мира', type:'lore', folders:['мир и история','страны и города','Нингард','районы','организации','религия','роды','паспорта и статус','еретики','болезни','законы и наказания','важные предметы','пророчества','здания, мосты, статуи, архивы, лазареты','Новое / требует уточнения'], fields:['папка','название','описание','канон','рабочие идеи','требует уточнения','заметки']},
  paths:{title:'Пути', type:'path', seed:['Архивы','Стражи','Лазаретные Хранители','Путь Образа и Слова'], fields:['название','цель','обучение','наставники','ученики','правила','символы','одежда','конфликты','сцены','заметки']},
  arts:{title:'Боевые искусства', type:'art', fields:['название','философия','история','сильные стороны','опасности','запреты','приёмы','носители','сцены, где используется','заметки и неразрешённое']},
  holidays:{title:'Праздники и традиции', type:'holiday', fields:['название','смысл','происхождение','традиции','символы','важные предметы','приметы','визуальная атмосфера','сцены, связанные с праздником','вопросы без ответа']},
  relations:{title:'Связи и отношения', type:'relation', fields:['персонаж','связанный персонаж','тип связи','связанные сцены','заметки']},
  unresolved:{title:'Неразрешённое', type:'unresolved', fields:['тип','название','описание','связанные записи','статус','заметки']},
  backup:{title:'Резервная копия', type:'backup'}
};
const relationTypes = ['дружба','любовь','ревность','конфликт','семья','долг','страх','тайна','вражда','уважение'];
let db = load(); let active = 'scenes'; let editing = null;
function emptyDb(){return Object.fromEntries(Object.keys(sections).map(k=>[k,[]]));}
function load(){const saved=localStorage.getItem(STORE_KEY); const data=saved?JSON.parse(saved):emptyDb(); if(!data.paths?.length) data.paths = sections.paths.seed.map(name=>record({название:name})); return {...emptyDb(),...data};}
function save(){localStorage.setItem(STORE_KEY, JSON.stringify(db)); render();}
function record(values={}){return {id:crypto.randomUUID(), createdAt:new Date().toISOString(), ...values};}
function $(s){return document.querySelector(s)};
function text(v){return (v||'').toString().replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]));}
function renderTabs(){ $('#tabs').innerHTML=Object.entries(sections).map(([k,s])=>`<button class="${k===active?'active':''}" data-tab="${k}">${s.title}</button>`).join('');}
function renderStats(){ $('#stats').innerHTML=[['scenes','сцен'],['characters','персонажей'],['lore','лора'],['unresolved','вопросов']].map(([k,l])=>`<div class="stat"><b>${db[k].length}</b><span>${l}</span></div>`).join('');}
function render(){renderTabs();renderStats(); const s=sections[active]; $('#content').innerHTML = active==='backup'?backupHtml():sectionHtml(active,s); bind();}
function sectionHtml(key,s){const q=$('#globalSearch').value.toLowerCase(); let items=db[key].filter(r=>JSON.stringify(r).toLowerCase().includes(q)); return `<h2>${s.title}</h2>${installNote()}<div class="toolbar"><button class="primary" data-add="${key}">Добавить</button>${key==='scenes'?'<button data-view="timeline">Лента сцен</button>':''}</div>${s.folders?foldersHtml(s):''}<div class="${key==='scenes'?'timeline ':''}cards" id="cards">${items.length?items.map(r=>cardHtml(key,r)).join(''):'<div class="empty">Пока пусто. Добавьте первую запись-шаблон.</div>'}</div>`;}
function foldersHtml(s){return `<div class="folder-grid">${s.folders.map(f=>`<div class="folder">${f}</div>`).join('')}</div>`;}
function cardHtml(key,r){const title=r.название||r.имя||r.персонаж||'Без названия'; const st=r['статус записи']||r.статус; let extra=key==='relations'?`<div class="link-line">${text(r.персонаж)} → ${text(r['связанный персонаж'])}<br>${text(r['тип связи'])}</div>`:''; return `<article class="card" draggable="${key==='scenes'}" data-id="${r.id}"><h3>${text(title)}</h3>${st?`<span class="badge ${statusClass[st]||'idea'}">${text(st)}</span>`:''}${extra}<div class="meta">${Object.entries(r).filter(([k,v])=>!['id','createdAt'].includes(k)&&v).slice(0,5).map(([k,v])=>`<span><b>${text(k)}:</b> ${text(v).slice(0,120)}</span>`).join('')}</div><div class="card-actions"><button data-edit="${r.id}">Открыть</button><button data-del="${r.id}">Удалить</button></div></article>`;}
function backupHtml(){return `<h2>Резервная копия</h2>${installNote()}<div class="cards"><button class="primary" id="exportJson">Экспорт всей базы в JSON</button><label class="card">Импорт JSON<input id="importJson" type="file" accept="application/json"></label><button id="exportTxt">Экспорт заметок в TXT</button><button id="wipe">Удалить все данные</button></div>`;}
function installNote(){return `<p class="install-note">PWA сохраняет данные локально и после первого открытия работает офлайн. В Chrome на Android: меню ⋮ → «Добавить на главный экран».</p>`}
function bind(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{active=b.dataset.tab;render()});document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>openEditor(b.dataset.add));document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEditor(active,b.dataset.edit));document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{if(confirm('Удалить запись?')){db[active]=db[active].filter(x=>x.id!==b.dataset.del);save();}});bindBackup();bindDrag();}
function openEditor(key,id){editing={key,id}; const s=sections[key], r=id?db[key].find(x=>x.id===id):record(); $('#editorTitle').textContent=(id?'Редактировать: ':'Новая запись: ')+s.title; $('#editorFields').innerHTML=s.fields.map(f=>fieldHtml(f,r[f])).join(''); $('#editorDialog').showModal();}
function fieldHtml(f,v=''){ if(f.includes('статус')) return `<div class="field"><label>${f}</label><select name="${f}">${statuses.map(x=>`<option ${x===v?'selected':''}>${x}</option>`)}</select></div>`; if(f==='тип связи') return `<div class="field"><label>${f}</label><select name="${f}">${relationTypes.map(x=>`<option ${x===v?'selected':''}>${x}</option>`)}</select></div>`; return `<div class="field"><label>${f}</label><textarea name="${f}" placeholder="Заполнить позже">${text(v)}</textarea></div>`;}
$('#editorForm').onsubmit=e=>{e.preventDefault(); const data=Object.fromEntries(new FormData(e.target).entries()); if(editing.id){Object.assign(db[editing.key].find(x=>x.id===editing.id),data)}else db[editing.key].push(record(data)); $('#editorDialog').close(); save();};
$('#globalSearch').oninput=render;document.querySelectorAll('[data-quick]').forEach(b=>b.onclick=()=>{active=b.dataset.quick;render();openEditor(active)});document.querySelectorAll('[value=cancel]').forEach(b=>b.onclick=()=>$('#editorDialog').close());
function bindBackup(){const ex=$('#exportJson'); if(!ex)return; ex.onclick=()=>download('archive-broken-soul.json',JSON.stringify(db,null,2),'application/json'); $('#exportTxt').onclick=()=>download('archive-broken-soul.txt',toText(),'text/plain'); $('#wipe').onclick=()=>{if(confirm('Точно удалить всю локальную базу?')){db=emptyDb();save();}}; $('#importJson').onchange=e=>{const file=e.target.files[0]; if(!file)return; file.text().then(t=>{db={...emptyDb(),...JSON.parse(t)};save();});};}
function download(name,body,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([body],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function toText(){return Object.entries(db).map(([k,arr])=>`# ${sections[k].title}\n`+arr.map(r=>Object.entries(r).filter(([x])=>!['id','createdAt'].includes(x)).map(([x,v])=>`${x}: ${v}`).join('\n')).join('\n---\n')).join('\n\n');}
function bindDrag(){let dragged; document.querySelectorAll('#cards .card[draggable=true]').forEach(c=>{c.ondragstart=()=>{dragged=c;c.classList.add('dragging')};c.ondragend=()=>c.classList.remove('dragging');c.ondragover=e=>e.preventDefault();c.ondrop=e=>{e.preventDefault(); const ids=[...document.querySelectorAll('#cards .card')].map(x=>x.dataset.id); const from=ids.indexOf(dragged.dataset.id), to=ids.indexOf(c.dataset.id); const [m]=db.scenes.splice(from,1); db.scenes.splice(to,0,m); save();};});}
if('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js');
render();
